### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by cole-brokamp** [jessecambon/tidygeocoder#128]
Hello!  I am listing two smaller review points here for my JOSS review (https://github.com/openjournals/joss-reviews/issues/3544)

- consider combining LICENSE.md and LICENSE into one file to prevent confusion
- please add a section title called "Statement of Need"; I believe this is sufficiently described, but just need to organize it into a section with this specific title

**Comment by jessecambon** [comment]
Hi @cole-brokamp, thanks. To your second bullet, the middle section "Challenges in Geocoding" is the statement of need. I can just change that section title to be "Statement of Need" if that would work for you.

To your first bullet, while I agree in principle, the CRAN regulations prevent this:

> Complete and ship as file LICENSE the following 2
lines (only)

>YEAR:
COPYRIGHT HOLDER: 

> and specify as

> License: MIT + file LICENSE
-https://cran.r-project.org/web/licenses/MIT 

You can see a more extended discussion on this topic here: https://github.com/tidyverse/tidyr/issues/262.

**Comment by dieghernan** [comment]
Very common problem on JOSS reviews due to CRAN policy, see also https://github.com/kadyb/rgugik/issues/61

**Comment by cole-brokamp** [comment]
Thanks for the information.  I don't think there is anything that can be done about the LICENSE files.  I think that renaming the middle section as Statement of Need would work to satisfy JOSS requirements.

**Comment by jessecambon** [comment]
Sounds good, I just made that change:

https://github.com/jessecambon/tidygeocoder/commit/a111b67881eaafc8277fba792d564a58016726f5
