### ISSUE TITLE
reverse_geo fails if input is multiple identical pairs of coordinates

### ISSUE THREAD

**Issue by long39ng** [jessecambon/tidygeocoder#129]
`reverse_geo` throws an error if I supply the same pair of coordinates multiple times _and_ the input has only one unique pair of coordinates.

If I supply the same pair of coordinates multiple times, but this is not the only unique pair, reverse geocoding works fine. Here's a minimal example:

``` r
suppressPackageStartupMessages(library(dplyr))
library(tidygeocoder)

df <- tibble(lat = 0, long = 0)

df |> 
  reverse_geocode(lat = lat, long = long)
#> # A tibble: 1 × 3
#>     lat  long address  
#>   <dbl> <dbl> <chr>    
#> 1     0     0 Soul Buoy
  
df[rep(1, 5), ] |> 
  reverse_geocode(lat = lat, long = long)
#> Error in vapply(elements, encode, character(1)): values must be length 1,
#>  but FUN(X[[2]]) result is length 5

df[rep(1, 5), ] |> 
  add_row(lat = 10, long = 10) |> 
  reverse_geocode(lat = lat, long = long)
#> # A tibble: 6 × 3
#>     lat  long address                    
#>   <dbl> <dbl> <chr>                      
#> 1     0     0 Soul Buoy                  
#> 2     0     0 Soul Buoy                  
#> 3     0     0 Soul Buoy                  
#> 4     0     0 Soul Buoy                  
#> 5     0     0 Soul Buoy                  
#> 6    10    10 Mun-Munsal, Bauchi, Nigeria
```

<sup>Created on 2021-08-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

(`geo`, however, works fine if the same location string is supplied multiple times.)

**Comment by jessecambon** [comment]
Thanks for reporting this. The issue was that in the [reverse_geo()](https://github.com/jessecambon/tidygeocoder/blob/main/R/reverse_geo.R) function the set of (duplicated) coordinates was being put into the query instead of the single unique coordinate.

You can install the bug fix from the main GitHub branch for now:

```r
devtools::install_github("jessecambon/tidygeocoder")
```
