### ISSUE TITLE
reverse geocodoing with tidygeocoder and OSM/Nominatim: Get results in latin letters/English?

### ISSUE THREAD

**Issue by werkstattcodes** [jessecambon/tidygeocoder#159]
First, many thanks for this wonderful package.

I am reverse geocoding coordinates which pertain to addresses in countries where the Cyrillic alphabet is used. I am using `tidygeocoder` and `OSM/Nominatim` as a method. Am I correct, that currently it's not possible to specify the output language/alphabet? How can I modify my request in `tidygeocoder` to get the results/addresses not in Cyrillic but in Latin letters/in English?

As far as I can tell, the relevant property in the Nominatim/OSM API is `accept-language` (see [here][1] and [here][2]). But adding it to a tidygeocoder request seems not to work.

    library(tidygeocoder)
    library(tidyverse)
    
    df_res <- tibble(
      lat=41.992073,
      long=21.429506
    ) %>% 
      reverse_geocode(.,
                      lat=lat,
                      long=long,
                      address="address",
                      method="osm") 

The resulting address reads as

> Шпаркасе, Македонија, Водно, Центар, Скопје, Општина Центар, Град
> Скопје, Скопски СР, 1111, Северна Македонија

Modifying the request to (as suggested [here][3]):

    tibble(
      lat=41.992073,
      long=21.429506
    ) %>% 
      reverse_geocode(.,
                      lat=lat,
                      long=long,
                      address="address",
                      method="osm",
                      api_options = list(osm_accept_language="en")
      ) 

leads to an error:

    Error: Invalid parameter "osm_accept_language" used in the api_options argument. See ?reverse_geo

The error also occurs when using "osm_accept-language". Many thanks! 
PS: I had previously posted the same issue on SO but got no response. So, I hope it's ok to file the "issue" here.

  [1]: https://nominatim.org/release-docs/latest/api/Reverse/#language-of-results
  [2]: https://help.openstreetmap.org/questions/73250/nominatim-city-names
  [3]: https://jessecambon.github.io/tidygeocoder/reference/reverse_geo.html

**Comment by jessecambon** [comment]
Hi @werkstattcodes, try using `custom_query` instead of `api_options`. That will pass the parameter directly to the Nominatim API (see ?reverse_geo for details).

**Comment by werkstattcodes** [comment]
Indeed, this works! Many thanks. I had tried it before, but only now figured out that I have to put `accept-language` in quotation marks. Again, congrats for this great package.
```
df_res <- tibble(
  lat=41.992073,
  long=21.429506
) %>% 
  reverse_geocode(.,
                  lat=lat,
                  long=long,
                  address="address",
                  method="osm",
                  custom_query  = list("accept-language"="en-US"))
```

> 1  42.0  21.4 Sparkasse, Makedonija, Vodno, Centar, Skopje, Municipality of Centar, City of Skopje,~

**Comment by jessecambon** [comment]
@werkstattcodes awesome, glad it worked. That's interesting that you have to put the parameter name in quotes. I'm guessing that's because it has a hyphen in it.
