### ISSUE TITLE
LocationIQ query rate is too high (for the free tier)

### ISSUE THREAD

**Issue by mathesong** [jessecambon/tidygeocoder#166]
Thanks for the incredible package!!

I was running queries through several of the APIs, and everything worked perfectly except for LocationIQ, for which I would hit rate limits.  Their documentation states that 2 queries per minute are allowed on the free tier, but only 60 requests per minute.  So I was getting 60 successful queries followed by 60 failures each time I used this service.

I suppose it makes sense to query the full 2 per second if you only have a few queries, but slower if there are many - or perhaps just waiting out the rest of the minute after each 60.  Anyhow, I thought I would alert you to this.  Happy to submit a PR to this effect if you'd like.

All the best,
Granville

**Comment by jessecambon** [comment]
Hi @mathesong, thanks. For the next release, I'll plan on changing the default `min_time` (minimum number of seconds per query) value from 0.5 to 1 ([code link](https://github.com/jessecambon/tidygeocoder/blob/cfc1ca9f4533e387a9e9be8dfe6e8b380bf8d37d/data-raw/api_references.R#L22)). In the mean time, you can use the `min_time` argument to override the default (ie. `geocode(..., min_time = 1)`) .

**Comment by mathesong** [comment]
Ah, great!  I figured there was an input argument somewhere to modify, but it wasn't a problem as I just ran another service to geocode the rest.  But your updating the default `min_time` is great: I was looking through the code and just never found where it was.

Thanks again for a stellar package!

**Comment by clarelgibson** [comment]
Thanks so much for posting this. I was looking for an argument called "delay" or similar and completely skipped over the "min_time". This really helped me.
