### ISSUE TITLE
Feature Request: parse addresses into city, state, zip (reverse_geocode argument)

### ISSUE THREAD

**Issue by RickPack** [jessecambon/tidygeocoder#170]
Might an argument be added to parse out the city, state, and zip from the address provided by `reverse_geocode()`?

Or might someone point me to a function to do so?

Example addresses:
```
Marketplace, Civic Center, Downtown, Los Angeles, Los Angeles County, California, United States 
Glenwaye Drive, Merrifield Park, Rogers Valley Heights, Greenville County, South Carolina, 29615, United States
Lakewood Gulch, Villa Park, Denver, Colorado, 80204, United States
```

Notice the inconsistent display of county and even zip.

They come from:
```
  latitude longitude
     34.9     -82.3
     41.9     -87.6
     39.7    -105. 
```

**Comment by jessecambon** [comment]
Hi @RickPack is this output from Nominatim? (ie. `method='osm'`)

Some address parsers you could consider:

- [postmastr](https://slu-opengis.github.io/postmastr/index.html) 
- If you are OK using python: [usaddress](https://parserator.datamade.us/usaddress/) is a package I've found to be pretty reliable in the past

**Comment by RickPack** [comment]
Wow, I do not remember what I google'd but it was obviously not "parse addresses rstats". Thank you!
