### ISSUE TITLE
reverse_geo not working

### ISSUE THREAD

**Issue by zachasman** [jessecambon/tidygeocoder#173]
Hello,

I am trying to reverse geocode. But when I copy the code verbatim from your[ own documentation](https://cran.r-project.org/web/packages/tidygeocoder/vignettes/tidygeocoder.html) I'm met with an error:

```
options(tidygeocoder.progress_bar = FALSE)
reverse_geo(lat = 38.895865, long = -77.0307713, method = 'osm')
reverse_geo(
  lat = c(38.895865, 43.6534817, 300),
  long = c(-77.0307713, -79.3839347, 600),
  method = 'osm', full_results = TRUE
)
```

Yields the following error:

```
Error in `vec_as_location()`:
! `...` must be empty.
✖ Problematic argument:
• call = call
Run `rlang::last_error()` to see where the error occurred.
```

What's happening?

**Comment by jessecambon** [comment]
Hi @zachasman can you post the results of `rlang::last_error()` so we can see where the error happened (mentioned in the traceback)? Also please post the results of `devtools::session_info()` so we can see what package versions are involved.

**Comment by zachasman** [comment]
@jessecambon  Sure thing.

`rlang::last_error()` produces:

```
Backtrace:
 1. tidygeocoder::reverse_geo(...)
 2. tidygeocoder:::package_inputs(...)
 5. tibble:::`[.tbl_df`(input_unique, !names(input_unique) %in% c(".uid"))
 6. tibble:::vectbl_as_col_location(...)
 9. vctrs::vec_as_location(j, n, names, call = call)
```

While `devtools::session_info()` produces:

`V tidygeocoder  * 1.0.5    2022-08-02 [1] Github (jessecambon/tidygeocoder@1aebc36) (on disk 1.0.5.9000)`

**Comment by zachasman** [comment]
@jessecambon  Do you need any more information?

**Comment by jessecambon** [comment]
No I think that's enough info. I haven't gotten a chance to reproduce it yet, but I'm guessing it's tied to the version of vctrs. What happens if you update that package to the newest version?

**Comment by zachasman** [comment]
@jessecambon Nevermind I updated all the packages and now it seems to be working.

**Comment by jessecambon** [comment]
@zachasman glad to hear it. Would you mind posting your (working) devtools::session_info() ?

When I get some time I want to see what is going on. Maybe there is a certain combination of package versions that creates a problem.
