### ISSUE TITLE
Different results when using method=”google” and search on maps.google.com

### ISSUE THREAD

**Issue by werkstattcodes** [jessecambon/tidygeocoder#184]
## Description

I am geo-coding an address with tidygeocoder::geo, method="google". If I put the obtained geo-coordinates into a link, I get the pertaining position on google maps.

Strikingly, this position is different than the position I obtain when putting the same address directly into google maps. 

In short, tidygeocoder returns a different pair of coordinates than the search on google maps. 

This is only for some addresses – in most cases the results are identical – but the deviation is nevertheless striking. Any idea what this could be due to? Many thanks.

## Steps to Reproduce
``` r
library(tidyverse)
library(tidygeocoder)

my_address <- "Rr. Ukshin Hoti nr. 124 , 10000 Prishtinë, Kosovo"

tgc_res <- tidygeocoder::geo(address = my_address, 
                             method="google", 
                             verbose=T) %>%
  mutate(branch_map_link=glue::glue("https://www.google.com/maps/dir//{lat},+{long}"))

tgc_res$branch_map_link
https://www.google.com/maps/dir//42.6629138,+21.1655028
```
Here the [link](https://www.google.com/maps/place/Banka+Komb%C3%ABtare+Tregtare+Kosov%C3%AB+SH.A./@42.658559,21.1538228,17z/data=!3m1!4b1!4m5!3m4!1s0x13549ee56da821cf:0xe6cae419edef072a!8m2!3d42.658559!4d21.1560168){target="_blank"} I obtain when inserting the address into google maps.

**Comment by jessecambon** [comment]
Hi @werkstattcodes, unfortunately I don't have too much insight into the inner workings of the Google geocoding service so it could be a question for Google if there are support people to reach out to over there. I would assume that the geocoding service would be what is behind Google Maps, but possibly they are also modifying the queries on Google Maps in some way? 

If you'd like to investigate further, here is a script that mimics what tidygeocoder does in the `geo()` function. However, this way you can see exactly what query is being submitted and the raw content being returned. 

``` r
library(tidygeocoder)
service <- "google"

generic_query <- list(address = "Rr. Ukshin Hoti nr. 124 , 10000 Prishtinë, Kosovo")

# add api key and default parameters (if any)
generic_query2 <- tidygeocoder:::add_common_generic_parameters(generic_query, service, FALSE, limit = 10)

# get api specific query
query_parameters <- get_api_query(
  service, generic_query2
)

api_url <- tidygeocoder:::get_google_url()

# execute the query
raw <- query_api(
  api_url,
  query_parameters
)

# parse the json content into a dataframe
results <- extract_results(service, jsonlite::fromJSON(raw$content))
```

Hope that helps, and let me know if you find out more about this.
