### ISSUE TITLE
Errors when geocoding

### ISSUE THREAD

**Issue by dobrowski** [jessecambon/tidygeocoder#19]
I'm getting the following output errors when trying to geocode

I'm running the follow line 
tidygeocoder::geocode(addr, lat=latitude, long=longitude, method = "cascade")

Opening and ending tag mismatch: meta line 6 and head
Opening and ending tag mismatch: br line 32 and div
Opening and ending tag mismatch: div line 21 and header
Entity 'times' not defined
Opening and ending tag mismatch: input line 116 and div
Opening and ending tag mismatch: input line 120 and div
Opening and ending tag mismatch: input line 127 and div
Opening and ending tag mismatch: input line 137 and div
Opening and ending tag mismatch: input line 136 and div
Opening and ending tag mismatch: input line 144 and div
Opening and ending tag mismatch: div line 139 and form
Opening and ending tag mismatch: input line 135 and div
AttValue: " or ' expected
attributes construct error
Couldn't find end of Start Tag div line 155
EntityRef: expecting ';'
EntityRef: expecting ';'
Opening and ending tag mismatch: input line 134 and div
Entity 'copy' not defined
Opening and ending tag mismatch: br line 214 and p
Opening and ending tag mismatch: p line 213 and footer
Opening and ending tag mismatch: footer line 209 and body
Opening and ending tag mismatch: input line 133 and html
Premature end of data in tag input line 132
Premature end of data in tag div line 131
Premature end of data in tag div line 129
Premature end of data in tag div line 125
Premature end of data in tag form line 124
Premature end of data in tag div line 119
Premature end of data in tag div line 115
Premature end of data in tag div line 111
Premature end of data in tag header line 20
Premature end of data in tag body line 18
Premature end of data in tag head line 3
Premature end of data in tag html line 2
Error: 1: Opening and ending tag mismatch: meta line 6 and head
2: Opening and ending tag mismatch: br line 32 and div
3: Opening and ending tag mismatch: div line 21 and header
4: Entity 'times' not defined
5: Opening and ending tag mismatch: input line 116 and div
6: Opening and ending tag mismatch: input line 120 and div
7: Opening and ending tag mismatch: input line 127 and div
8: Opening and ending tag mismatch: input line 137 and div
9: Opening and ending tag mismatch: input line 136 and div
10: Opening and ending tag mismatch: input line 144 and div
11: Opening and ending tag mismatch: div line 139 and form
12: Opening and ending tag mismatch: input line 135 and div
13: AttValue: " or ' expected
14: attributes construct error
15: Couldn't find end of Start Tag div line 155
16: EntityRef: expecting ';'
17: EntityRef: expecting ';'
18: Opening and ending tag mismatch: input line 134 and div
19: Entity 'copy' not defined
20: Opening and ending tag mismatch: br line 214 and p
21: O

**Comment by jessecambon** [comment]
Can you provide a reproducible example? https://www.tidyverse.org/help/

**Comment by jessecambon** [comment]
@dobrowski could you post the results of devtools::session_info() ? I'm guessing there is a package dependency issue.

**Comment by dobrowski** [comment]
─ Session info ──────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       macOS Mojave 10.14.6        
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2020-06-02                  

─ Packages ──────────────────────────────────────────────────────────────────
 package       * version    date       lib
 askpass         1.1        2019-01-13 [1]
 assertthat      0.2.1      2019-03-21 [1]
 backports       1.1.5      2019-10-02 [1]
 bitops          1.0-6      2013-08-17 [1]
 broom           0.5.4      2020-01-27 [1]
 callr           3.4.1      2020-01-24 [1]
 cellranger      1.1.0      2016-07-27 [1]
 class           7.3-15     2019-01-01 [1]
 classInt        0.4-2      2019-10-17 [1]
 cli             2.0.2      2020-02-28 [1]
 codetools       0.2-16     2018-12-24 [1]
 colorspace      1.4-1      2019-03-18 [1]
 crayon          1.3.4      2017-09-16 [1]
 curl            4.3        2019-12-02 [1]
 DBI             1.1.0      2019-12-15 [1]
 dbplyr          1.4.2      2019-06-17 [1]
 desc            1.2.0      2018-05-01 [1]
 devtools        2.2.1      2019-09-24 [1]
 dichromat       2.0-0      2013-01-24 [1]
 digest          0.6.25     2020-02-23 [1]
 dplyr         * 0.8.4      2020-01-31 [1]
 e1071           1.7-3      2019-11-26 [1]
 ellipsis        0.3.1      2020-05-15 [1]
 fansi           0.4.1      2020-01-08 [1]
 forcats       * 0.4.0      2019-02-17 [1]
 fs              1.3.1      2019-05-06 [1]
 gargle          0.4.0      2019-10-04 [1]
 generics        0.0.2      2018-11-29 [1]
 ggmap         * 3.0.0      2019-02-05 [1]
 ggplot2       * 3.3.0.9000 2020-01-30 [1]
 glue            1.4.1      2020-05-13 [1]
 googledrive     1.0.0      2019-08-19 [1]
 googlesheets4 * 0.1.0.9000 2020-01-31 [1]
 gtable          0.3.0      2019-03-25 [1]
 haven           2.2.0      2019-11-08 [1]
 here          * 0.1        2017-05-28 [1]
 hms             0.5.3      2020-01-08 [1]
 httr            1.4.1      2019-08-05 [1]
 jpeg            0.1-8.1    2019-10-24 [1]
 jsonlite        1.6.1      2020-02-02 [1]
 KernSmooth      2.23-16    2019-10-15 [1]
 lattice         0.20-38    2018-11-04 [1]
 lifecycle       0.2.0      2020-03-06 [1]
 lubridate       1.7.4      2018-04-11 [1]
 lwgeom          0.2-1      2020-01-31 [1]
 magrittr        1.5        2014-11-22 [1]
 memoise         1.1.0      2017-04-21 [1]
 modelr          0.1.5      2019-08-08 [1]
 munsell         0.5.0      2018-06-12 [1]
 nlme            3.1-139    2019-04-09 [1]
 openssl         1.4.1      2019-07-18 [1]
 packrat         0.5.0      2018-11-14 [1]
 pillar          1.4.4      2020-05-05 [1]
 pkgbuild        1.0.6      2019-10-09 [1]
 pkgconfig       2.0.3      2019-09-22 [1]
 pkgload         1.0.2      2018-10-29 [1]
 plyr            1.8.5      2019-12-10 [1]
 png             0.1-7      2013-12-03 [1]
 prettyunits     1.1.1      2020-01-24 [1]
 processx        3.4.1      2019-07-18 [1]
 ps              1.3.0      2018-12-21 [1]
 purrr         * 0.3.4      2020-04-17 [1]
 R6              2.4.1      2019-11-12 [1]
 raster          3.0-12     2020-01-30 [1]
 RColorBrewer    1.1-2      2014-12-07 [1]
 Rcpp            1.0.3      2019-11-08 [1]
 readr         * 1.3.1      2018-12-21 [1]
 readxl        * 1.3.1      2019-03-13 [1]
 remotes         2.1.0      2019-06-24 [1]
 reprex          0.3.0      2019-05-16 [1]
 rgdal           1.4-8      2019-11-27 [1]
 rgeocodio     * 0.3.0      2020-05-20 [1]
 rgeos           0.5-2      2019-10-03 [1]
 RgoogleMaps     1.4.5.2    2020-01-26 [1]
 rjson           0.2.20     2018-06-08 [1]
 rlang           0.4.6      2020-05-02 [1]
 rprojroot       1.3-2      2018-01-03 [1]
 rstudioapi      0.10       2019-03-19 [1]
 rvest           0.3.5      2019-11-08 [1]
 scales          1.1.0      2019-11-18 [1]
 sessioninfo     1.1.1      2018-11-05 [1]
 sf              0.8-1      2020-01-28 [1]
 sp              1.3-2      2019-11-07 [1]
 stringi         1.4.5      2020-01-11 [1]
 stringr       * 1.4.0      2019-02-10 [1]
 testthat        2.3.1      2019-12-01 [1]
 tibble        * 3.0.1      2020-04-20 [1]
 tidygeocoder    0.2.5      2020-03-22 [1]
 tidyr         * 1.0.2      2020-01-24 [1]
 tidyselect      1.0.0      2020-01-27 [1]
 tidyverse     * 1.3.0      2019-11-21 [1]
 tmaptools       2.0-2      2019-07-18 [1]
 units           0.6-5      2019-10-08 [1]
 usethis         1.5.1      2019-07-04 [1]
 vctrs           0.3.0      2020-05-11 [1]
 viridisLite     0.3.0      2018-02-01 [1]
 withr           2.1.2      2018-03-15 [1]
 XML             3.99-0.3   2020-01-20 [1]
 xml2            1.2.2      2019-08-09 [1]
 source                                  
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 Github (tidyverse/ggplot2@214f314)      
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 Github (tidyverse/googlesheets4@b86b6f7)
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 standard (@1.1.0)                       
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 standard (@1.0.2)                       
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 Github (hrbrmstr/rgeocodio@98fff15)     
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 standard (@1.1.1)                       
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.2)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          
 CRAN (R 3.6.0)                          

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library

**Comment by jessecambon** [comment]
To generate the error in your initial post, you are using the inbuilt 'sample_addresses' datasets, correct? Do the other methods ('census' and 'osm') work properly? The traceback could tell you which package it is coming from.
