### ISSUE TITLE
Allow storing api key in code instead of .Renviron

### ISSUE THREAD

**Issue by rcepka** [jessecambon/tidygeocoder#195]
My particular need is for BING, but I guess the question is relevant also for other providers.

As I understood from docs, api credentials are required to be stored in .Renviron. 
I would like to be able to do something like this:
`
df_geocoded <- df_base %>%
    tidygeocoder::geocode(
      address = location,
      method = "bing",
      lat = "lat",
      long = "long",
      custom_query = list(
        token = "myapi"
        )
      )
`
The above does not work for my for BING.

My need is motivated by fact, that I will deploy my app in Docker container, so I guess geocoding will not work, because the API key is stored in my local .Renviron.
Do you have any recommendation for deploying app in container please?

Thanks in advance for any hints or advices..

**Comment by jessecambon** [comment]
Hi @rcepka, I think for your use case you could use `Sys.setenv()`

https://stat.ethz.ch/R-manual/R-devel/library/base/html/Sys.setenv.html

**Comment by rcepka** [comment]
My solution: I created a custom .Renviron file for this particular project in the project root directory, where I put the API key. This file is being copied to the container within the other code, so the credentials are sustained.

This solution seems to work for me.

Thank you @jessecambon for your help and hints.
