### ISSUE TITLE
Parallelize geocoding 

### ISSUE THREAD

**Issue by twesleyb** [jessecambon/tidygeocoder#20]
Hey @jessecambon,
Do you think it would be possible to parallelize the geocoding task?
Or I might just be impatient...

```
* Project '/mnt/d/projects/tidygeocoder' loaded. [renv 0.10.0]

Evaluating time needed to geocode 100 addresses...
Unit: seconds
                     expr      min       lq     mean   median       uq      max
 geocode(x100_rows, ADDR) 14.76898 14.96446 15.15467 15.15994 15.34751 15.53508
 neval
     3

Predicted time to encode 88,303 addresses: 3.717 hours.
```

**Comment by jessecambon** [comment]
Which geocoding service are you using for this? Batch geocoding might be something to look into and is something I'm planning on looking into. I think OSM doesn't encourage batch geocoding from what I've seen but Census.

Also, if you want to quickly geocode that many addresses, you might want to look into a commercial geocoding plan. I'm working on implementing support for a couple services that have free and commercial tiers #15 (and also support batch queries).
