### ISSUE TITLE
Installing package

### ISSUE THREAD

**Issue by codefromjames** [jessecambon/tidygeocoder#36]
I try to install tidygeocoder into R

install.packages("tidygeocoder",dependencies = TRUE)
but received;
ERROR: this R is version 3.4.3, package 'tidygeocoder' requires R >= 3.20

Which appears it is requesting R version 3.twenty which does not exist. I have tried install_gub and source install from github directly but the same error. Am I missing something obvious to resolve?

r package version

**Comment by jessecambon** [comment]
This was a typo in the R version ( #35 )

It is fixed on the master branch, though. Does this command work?

```r
devtools::install_github("jessecambon/tidygeocoder")
```

**Comment by codefromjames** [comment]
All good, thank for your dedication.
