### ISSUE TITLE
Installing tidygeocoder - correct R version?

### ISSUE THREAD

**Issue by alynnz** [jessecambon/tidygeocoder#37]
Do you have any suggestions on which version of R to use to install tidygeocoder? I've attempted installing it with R/3.5.1 and R/3.2.0, but got error messages both times saying the package was unavailable. Thank you!

**Comment by jessecambon** [comment]
See #35 (install from github master branch for now). Will be fixed in the next release sent to CRAN.

**Comment by alynnz** [comment]
Thank you!
