### ISSUE TITLE
Progress bar?

### ISSUE THREAD

**Issue by mikedolanfliss** [jessecambon/tidygeocoder#38]
Hi there, fantastic package. Exciting standardization, as I've been writing my own API wrappers or using any of the other less-tidyverse-friendly geocoding packages.

Any thoughts on adding progress bars (like readr enables for long lists)? geo() could be wrapped to achieve this (using progress package or otherwise), but some intelligence to recognize larger geocode requests worth progress-bar-ing might be valuable.

FWIW. Best wishes again on this great package.

**Comment by jessecambon** [comment]
Thanks! I did write myself a note in the past to add a progress bar (#17), but ended up prioritizing other items for this latest release. Implementing a progress bar when using a separate HTTP query for each address (ie. not batch geocoding) should be fairly straightforward. However, I'm not sure if there is a way to get the realtime progress of a batch request. 

Out of curiosity, how many addresses are you typically trying to geocode at once and which geocoder services are you using?

**Comment by mikedolanfliss** [comment]
I semi-regularly geocode a few thousand to tens of thousands at once. I've been using either hand-written API calls to the census batch geocoder (not ideal), or the ggmap package with a simple throttle-adjusting version of ggmap::geocode() with my credentials. 
```
# > Function to avoid throttling ####
slow_geocode = function(...){Sys.sleep(0.1); ggmap::geocode(...)} 
```
The timing for the various services varies pretty wildly. One idea I had with batches (and something I do myself) is, for large batches, first send a small test batch (10-100) and time it (many timing options, I often use tictoc). Then extrapolate. Not perfect, but in the case of large batches, even a time-based-progress bar might be a clever workaround. Or perhaps just, in the meantime, default to "if progress bar -->separate API calls". 

Best wishes again for this amazing package progress. Standardized, accessible geocoding (with or without an API key) is a huge need I've worked around for years, and this is one of the most exciting package developments I've seen. 

While I'm at suggesting things :), there was once heady on the data-science toolkit on using a local master address database to geocode - much more sustainable for big calls when someone can, for instance, download all geocoded addresses in a state or county and work off that (the way SAS or ArcGIS can). That to me feels like a missing keystone to a complete geocode package, though would be a sizable lift. I'll be watching this package and if there are ways I can contribute (ahem, after COVID, since I'm an overworked epidemiologist at the moment) I'd love to. Again, thanks for the work. I'll tag this possibility in a separate idea.

**Comment by jessecambon** [comment]
Thanks for the info and suggestions. Are the issues you run into with the Census geocoder related to accuracy, missing results, or speed? 

For progress bars, one simple approach could be to include a progress bar when there is one address per API call and for batch geocoding include a timer (that just counts up) with the number of addresses in the batch.

**Comment by mikedolanfliss** [comment]
Mostly missing results - I do have current project where I'm geocoding a few thousand addresses multiple ways (so could gesture at accuracy). The census is also often slow by api, at least relative to Google. But the batch system seems efficient.

I think your progress bar idea (count down vs time elapsed for batch) sounds excellent. Technically, though this would be clever, the package could save an internal table of submitted batches and times and try to leverage that for time estimation. But again, would require cleverness.

**Comment by jessecambon** [comment]
The development version (main branch) now has progress bars for single input geocoding (ie. not batch geocoding) and will be included in the next release. Can revisit progress bars for batch jobs in the future, but I think that would require parallel processing and would only be able to count up (ie. no progress updates).
