### ISSUE TITLE
Geocodio example

### ISSUE THREAD

**Issue by AgentRatty** [jessecambon/tidygeocoder#43]
I looked but did not find an example of how to set up tidygeocoder to use geocodio. Is there a code sample that you could point me to?

Thanks

**Comment by jessecambon** [comment]
You can use geocodio by specifying it with the `method` argument in either `geo()` or `geocode()`. Refer to the [geo()](https://jessecambon.github.io/tidygeocoder/reference/geo.html) documentation for details. 

The reason why there isn't a Geocodio (or Location IQ) example in the vignette or documentation examples is that this code has to run on CRAN where there would not be an installed API key. I could create a page on the package site (not a vignette) to show example usage, though.

**Comment by AgentRatty** [comment]
Thank you...I figured it out.

Not a biggie but ggmap has a function that munges your data frame with the API results...tidy if you want to keep track of other values (such as row identifier, for joining to other data sets)...You pass DataFrame and column that contains addresses and you get back the data frame with the results.

`mutate_geocode(tblSqlData, FullAddr, output = "more", source = "google")`

Looks like its not too complex, though it would require a dependency on dplyr

`{
    locs <- data[[deparse(substitute(location))]]
    gcdf <- geocode(locs, ...)
    dplyr::bind_cols(data, gcdf)
}`

**Comment by jessecambon** [comment]
You should be able to do this with `geocode()`. Try something like this:

```r
output <- your_input_df %>%
    tidygeocoder::geocode(address_column_name, method = 'geocodio', full_results = TRUE)
```


```
