### ISSUE TITLE
forward geocoding is stopped when LocationIQ API respond HTTP Error

### ISSUE THREAD

**Issue by dsolito** [jessecambon/tidygeocoder#46]
Hello,

when an address is badly encoded,  LocationIQ respond an 404 Response Code.

`Not Found (HTTP 404).Error in if (nrow(lat_lng) == 0 | ncol(lat_lng) != 2) return(NA_result) : 
  argument is of length zero`

The problem is that it stop the geocode() process and further entries are not geocoded.
When you have an table of 1000 entries, that's annoying.
It could be great if the function bypass the bad entry and continue the gecoding.

David

**Comment by jessecambon** [comment]
@dsolito thanks for reporting that. Do you have some examples of badly encoded addresses I could use to replicate this error?
