### ISSUE TITLE
Issue with custom_query and geocodio

### ISSUE THREAD

**Issue by MikeBurkePhD** [jessecambon/tidygeocoder#48]
First, thank you for the excellent package.

I am running into an issue where `custom_query` won't pull the requested fields from the geocodio API. 

Reproducible example requesting state legislative districts or Census tracts via the field keys `stateleg` and `tract_code`:

```

library(tidygeocoder)
library(tidyverse)

Sys.setenv(GEOCODIO_API_KEY = "INSERT YOUR KEY")

some_addresses <- tribble(
                       ~name,                  ~addr,
                       "White House",          "1600 Pennsylvania Ave, Washington, DC",
                       "Transamerica Pyramid", "600 Montgomery St, San Francisco, CA 94111",     
                       "Willis Tower",         "233 S Wacker Dr, Chicago, IL 60606"                                  
                       )

test <- some_addresses %>% geocode(
                                addr, method = "geocodio", 
                                full_results = TRUE,
                                custom_query = list(fields = 'stateleg')
                                )

test2 <- some_addresses %>% geocode(
                                 addr, method = "geocodio", 
                                 full_results = TRUE,
                                 custom_query = list(fields = 'tract_code')
                                 )
```
My expectation was that this would give me the information contained within the `stateleg` and `tract_code` keys from geocodio. This is the link to the relevent API documentaiton: [https://www.geocod.io/docs/?shell#fields](https://www.geocod.io/docs/?shell#fields).

I modeled this off the example in the `tidygeocoder` documentation for getting different vintages of census data (i.e., `list(vintage = 'Current_Census2010')`.

**Comment by jessecambon** [comment]
Thanks for reporting this. It looks like there was a simple oversight in the batch geocodio function (the custom_query argument just wasn't being passed). I put the fix on a separate branch and you can install it with this: 

```r
devtools::install_github("jessecambon/tidygeocoder", ref = 'fix/geocodio-batch-custom')
```

Hopefully that makes everything work as expected.

**Comment by MikeBurkePhD** [comment]
Yes, this is working perfectly now. Thanks for the update and quick reply! I really appreciate it.

Also, in case anyone is interested, here is an example of how to get the full FIPS information using 2019 Census information (including census tract, block, etc):

```
test2 <- some_addresses %>% geocode(
                                 addr, method = "geocodio", 
                                 full_results = TRUE,
                                 custom_query = list(fields = 'census2019, full_fips')
```

**Comment by ALFerino** [comment]
Hi jessecambon,
I am having a similar issue with custom_query but looking for Congressional District information.  

Is the fix above for MikeBurkePhD in the current tidygeocoder package or do i need a separate download?

Any help is much appreciated!

**Comment by jessecambon** [comment]
@ALFerino this fix is in the GitHub/development version of the package (master branch), but not the CRAN version yet.
