### ISSUE TITLE
Feature request: add geometry argument to pick between point and bbox from OSM

### ISSUE THREAD

**Issue by charliejhadley** [jessecambon/tidygeocoder#59]
The `tmaptools::geocode_OSM()` function has a useful argument `geometry = c("point", "bbox")` that allows users to request either coordinates of a bounding box for each geocode result.

I have an idea for how to implement this, but don't have capacity to do it right now - so this is issue is a stub for me.

**Comment by jessecambon** [comment]
@charliejhadley does `geometry = 'point'` find the center point of the `boundingbox` field that OSM returns?
