### ISSUE TITLE
Installation failed due to units/udunits2 dependency

### ISSUE THREAD

**Issue by twesleyb** [jessecambon/tidygeocoder#9]
Hi Jesse,
I'm excited to try your package, but I'm having some trouble. 
I don't think this is an issue with your package, but with its dependency `udunits2`.
My installation of `tidygeocoder` always fails:
`install.packages('tidyrgeocoder')` produces the error:
> ERROR: configuration failed for package ‘udunits2’.

So, I need `udunits2`. The error message prompts:
> If the udunits2 library is installed in a non-standard location
> use --configure-args='--with-udunits2-lib=/usr/local/lib'

I made sure that I have `udunits2` installed, `which udunits2`:
> /usr/bin/udunits2`

So, I tried installing again, specifying my `udunits2` location:
```
install.packages("units",configure.args="--with-udunits2-lib=/usr/bin/udunits2")
```

Forgive me, I know this is not a problem with your package. 

Any help is appreciated. 

-Tyler

**Comment by jessecambon** [comment]
Hi Tyler, no worries. I'm not familiar with that package, it must be a lower level dependency. I'm not sure what operating system you are on, but these threads might be helpful: 

https://github.com/r-quantities/units/issues/1
https://github.com/thomasp85/ggraph/issues/34

Good luck.

**Comment by twesleyb** [comment]
Hi Jesse, Thanks, if I'm able to find a solution, I'll post it here.

**Comment by twesleyb** [comment]
Alright, the problem arises from `tidygeocoder's` dependency on `tmaptools`-- which depends upon `units` which in turn depends upon the C library `udunits2`. After several failed attempts to install `units/udunits2`, I gave up and took a look at `tidygeocoder::geo_osm` -- the function that calls `tmaptools::geocode_OSM`. 

Since `geocode_OSM` itself doesn't use `units`, we don't really need this dependency. So, I added `geocode_OSM` to your `R/` directory and updated the package docs as necessary. I think everything is working now. If you want, you can incorporate these changes with my [pull request](https://github.com/jessecambon/tidygeocoder/pull/12).

**Comment by jessecambon** [comment]
@twesleyb very nice, thanks for submitting that PR. Glad you were able to find a solution and that's a good reduction in dependencies. I'll pull this into a new branch for testing and to make sure I understand the code. Let me know if you run into any other issues or have thoughts on other enhancements.

**Comment by jessecambon** [comment]
@twesleyb  Update - I pulled the code into https://github.com/jessecambon/tidygeocoder/tree/remove-tmaptools. However, it is failing due to a dependency on the tmaptools::bb function. 

Also the  limits for OSM geocoding usage are here: https://operations.osmfoundation.org/policies/nominatim/. Limiting the request rate to a max of 1 address per second seems to be the main restriction.

**Comment by twesleyb** [comment]
Hey @jessecambon, whoops, the `geocode_OSM` function contained a bunch of stuff you didn't need. It can be simplified. I cut most of it, and created a new function `query_osm.R` that queries OSM for an address and returns it latitude and longitude coordinates. This removes the `bb` (bounding box) dependency that came along with `geocode_OSM`--not sure why this passed before (maybe I accidentally had the tmaptools librrary still loaded?). `query_OSM` just uses __XML__ to parse the search result obtained from OSM--so I added this to the imports statement in the packages `DESCRIPTION`. Preliminary testing by running your `testthat.R` worked. I also successfully installed my fork with `devtools`, so far so good. I will perform some more tests soon--in the meantime, this the update:

IMO it still makes sense to replace the `tmaptools::geocode_OSM` dependency since you only use one function from this lib-- and from that one function, you only use a little bit of its capabilities. 

I use Windows, but I do all my coding and stuff on the Windows subsystem for Linux which runs Ubuntu. 

Thanks for the reference RE limits. I have an actual dataset that I'm working towards using your package for--this will be a pretty robust test.

**Comment by jessecambon** [comment]
@twesleyb nice, yes that looks much more manageable. Looks like there are some conflicts, but I'll resolve and merge when I get a chance to test it out. I'd also like to look at incorporating a Sys.sleep() call in the `query_osm` function to avoid the usage lockouts. Might be best to incorporate this as a function argument for flexibility.

**Comment by jessecambon** [comment]
@twesleyb  I merged your PR into the remove-tmaptools branch and merged query_OSM into geo_osm. Ran a few quick tests and everything seems to be working.

**Comment by twesleyb** [comment]
@jessecambon sounds great!

**Comment by jessecambon** [comment]
tmaptools is no longer a dependency in version 0.3.0.0
